---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/fhofherr/golf
    steps:
      - checkout
      - run: make test
